
services:
  mysql:
    image: mysql:8.0
    container_name: veri_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: verichat
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: veri_redis
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data


  prometheus:
    image: prom/prometheus:latest
    container_name: verichat_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: verichat_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
  mysql_data:
  redis_data: