
services:
  mysql:
    image: mysql:8.0
    container_name: veri_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: verichat
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: veri_redis
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data

volumes:
  mysql_data:
  redis_data:
